import Link from "next/link";
import AppHeader from "@/components/AppHeader";
import { getPendingTradeOffers } from "@/lib/trades/data";
import { getUserTradeOffers } from "@/lib/trades/data";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { hasDailyPullAvailable } from "@/lib/gacha/daily";
import TradeCancelButton from "@/components/TradeCancelButton";
import { LoginPromptButton } from "@/components/AuthPromptProvider";

export const metadata = { title: "Trades — AniGarden" };

export default async function TradesPage() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  const [{ data: transactions }, offers, myOffers] = await Promise.all([
    user ? supabase.from("gem_transactions").select("amount").eq("user_id", user.id).eq("status", "completed") : Promise.resolve({ data: [] }),
    getPendingTradeOffers(),
    user ? getUserTradeOffers(user.id) : Promise.resolve([]),
  ]);
  const gemBalance = (transactions ?? []).reduce((sum, transaction) => sum + transaction.amount, 0);
  const dailyPullAvailable = user ? await hasDailyPullAvailable(supabase, user.id) : false;
  const userName = user ? (typeof user.user_metadata?.nickname === "string" ? user.user_metadata.nickname : `user${user.id.replace(/-/g, "").slice(0, 6)}`) : "Guest";
  return <main className="min-h-screen bg-slate-950 px-6 py-8 sm:px-10"><div className="mx-auto max-w-5xl">
    <AppHeader gemBalance={gemBalance} dailyPullAvailable={dailyPullAvailable} userName={userName} avatarUrl={user ? (typeof user.user_metadata?.avatar_url === "string" ? user.user_metadata.avatar_url : null) : null} />
    <section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-lime-300">Peer-to-peer swaps</p><h1 className="mt-3 text-4xl font-bold text-white">Open trade offers.</h1><p className="mt-4 max-w-2xl leading-7 text-slate-400">Browse characters other gardeners are offering and choose what you want to give in return.</p></div>{user ? <Link href="/trades/create" className="rounded-xl bg-brand px-5 py-3 text-sm font-bold text-garden-950 transition hover:bg-lime-300">Create an offer →</Link> : <LoginPromptButton className="rounded-xl bg-brand px-5 py-3 text-sm font-bold text-garden-950 transition hover:bg-lime-300">Sign in to create an offer →</LoginPromptButton>}</div></section>
    <section className="mt-10"><div className="flex items-end justify-between gap-3"><h2 className="text-2xl font-bold text-white">All open offers</h2><span className="text-sm text-slate-500">{offers.length} open</span></div>{offers.length === 0 ? <p className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-8 text-center text-sm text-slate-400">No open offers yet. Create the first one.</p> : <div className="mt-6 grid gap-5 md:grid-cols-2">{offers.map((offer) => <Link key={offer.id} href={`/trades/${offer.share_token}`} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 transition hover:-translate-y-1 hover:border-lime-300/50"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-white">Character swap offer</p><p className="mt-1 text-xs text-slate-500">Created {new Date(offer.created_at).toLocaleDateString()}</p></div><span className="rounded-full bg-lime-300/10 px-3 py-1 text-xs font-bold text-lime-300">Open</span></div><div className="mt-4 flex -space-x-3">{offer.creatorItems.slice(0, 5).map((card) => <img key={card.id} src={card.image_url} alt={card.name} title={card.name} className="h-14 w-14 rounded-xl border-2 border-slate-900 object-cover" />)}{offer.creatorItems.length > 5 ? <span className="flex h-14 w-14 items-center justify-center rounded-xl border-2 border-slate-900 bg-slate-800 text-xs text-slate-300">+{offer.creatorItems.length - 5}</span> : null}</div><p className="mt-4 text-sm font-bold text-amber-200">✦ {offer.creatorValue.toLocaleString()} garden value</p><p className="mt-2 text-sm font-semibold text-lime-300">View offer →</p></Link>)}</div>}</section>
    <section className="mt-14"><div className="flex items-end justify-between gap-3"><div><h2 className="text-2xl font-bold text-white">My trade offers</h2><p className="mt-1 text-sm text-slate-400">Manage and share offers you created.</p></div><span className="text-sm text-slate-500">{user ? `${myOffers.length} total` : "Sign in required"}</span></div>{!user ? <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-8 text-center"><p className="text-sm text-slate-400">Sign in to see and manage your own offers.</p><LoginPromptButton className="mt-4 text-sm font-semibold text-lime-300 hover:text-lime-200">Sign in with Google</LoginPromptButton></div> : myOffers.length === 0 ? <p className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-8 text-center text-sm text-slate-400">You have not created any trade offers yet.</p> : <div className="mt-6 grid gap-5 md:grid-cols-2">{myOffers.map((offer) => <article key={offer.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/trades/${offer.share_token}`} className="font-semibold text-white hover:text-lime-200">Character swap offer</Link><p className="mt-1 text-xs text-slate-500">Created {new Date(offer.created_at).toLocaleDateString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${offer.status === "pending" ? "bg-lime-300/10 text-lime-300" : offer.status === "completed" ? "bg-sky-300/10 text-sky-300" : "bg-slate-800 text-slate-400"}`}>{offer.status}</span></div><div className="mt-4 flex -space-x-3">{offer.creatorItems.slice(0, 5).map((card) => <img key={card.id} src={card.image_url} alt={card.name} title={card.name} className="h-14 w-14 rounded-xl border-2 border-slate-900 object-cover" />)}{offer.creatorItems.length > 5 ? <span className="flex h-14 w-14 items-center justify-center rounded-xl border-2 border-slate-900 bg-slate-800 text-xs text-slate-300">+{offer.creatorItems.length - 5}</span> : null}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-amber-200">✦ {offer.creatorValue.toLocaleString()} garden value</p><div className="flex items-center gap-3"><Link href={`/trades/${offer.share_token}`} className="text-sm font-semibold text-lime-300 hover:text-lime-200">View/share →</Link>{offer.status === "pending" ? <TradeCancelButton token={offer.share_token} /> : null}</div></div></article>)}</div>}</section>
  </div></main>;
}
