import Link from "next/link";

export const metadata = {
  title: "Collect, grow, and trade anime characters",
  description: "AniGarden is a closed-loop anime character collection game with blooming pulls and asynchronous peer-to-peer trades.",
  alternates: { canonical: "/" },
};

export default function HomePage() {
  const structuredData = { "@context": "https://schema.org", "@type": "VideoGame", name: "AniGarden", description: "A closed-loop anime character collection game with blooming pulls and peer-to-peer trades.", genre: ["Collectible game", "Anime game"], applicationCategory: "Game", operatingSystem: "Web browser", url: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000" };
  return <main className="min-h-screen overflow-hidden bg-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} /><section className="relative border-b border-lime-300/10 bg-[radial-gradient(circle_at_top,_rgba(132,204,22,0.24),_transparent_58%)] px-6 py-20 sm:px-10 sm:py-28"><div className="relative mx-auto max-w-5xl"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-lime-300">A living collection game</p><h1 className="mt-5 text-5xl font-black tracking-tight text-white sm:text-7xl">Grow a garden full of rare anime characters.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Collect original residents, reveal blooming pulls, build your personal garden, and make asynchronous peer-to-peer trades with other gardeners.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard" className="rounded-xl bg-brand px-6 py-3.5 text-sm font-bold text-garden-950 transition hover:bg-lime-300">Explore the dashboard →</Link><Link href="/login" className="rounded-xl border border-slate-700 px-6 py-3.5 text-sm font-semibold text-slate-200 transition hover:border-lime-300/60">Start collecting</Link></div></div></div></section><section className="mx-auto grid max-w-5xl gap-5 px-6 py-16 sm:grid-cols-3 sm:px-10"><article className="rounded-2xl border border-lime-300/15 bg-garden-900/50 p-6"><p className="text-3xl">🌱</p><h2 className="mt-5 text-xl font-bold text-white">Discover characters</h2><p className="mt-3 text-sm leading-6 text-slate-400">Plant pulls to discover residents with different rarities, editions, and blooming levels.</p></article><article className="rounded-2xl border border-sky-300/15 bg-slate-900/70 p-6"><p className="text-3xl">✨</p><h2 className="mt-5 text-xl font-bold text-white">Build your garden</h2><p className="mt-3 text-sm leading-6 text-slate-400">Track your collection and garden value while every individual edition remains part of your inventory.</p></article><article className="rounded-2xl border border-fuchsia-300/15 bg-slate-900/70 p-6"><p className="text-3xl">🔁</p><h2 className="mt-5 text-xl font-bold text-white">Trade peer to peer</h2><p className="mt-3 text-sm leading-6 text-slate-400">Create a one-time trade link, offer specific copies, and request the characters you want in return.</p></article></section><section className="mx-auto max-w-5xl px-6 pb-20 text-center sm:px-10"><p className="text-sm leading-6 text-slate-500">AniGarden is a closed-loop digital game. Gems, characters, and garden value have no cash-out or real-world monetary value.</p></section></main>;
}
